package pack_age;
import java.io.*;

public class StringLen {

	public static void main(String[] args)throws IOException {//for handling exception from readLine method
		// TODO Auto-generated method stub
		System.out.println("Enter String : ");
		BufferedReader br=new BufferedReader(new InputStreamReader(System.in));
		String str=br.readLine();
		int len=0;
		try {
			while(true) {
				str.charAt(len++);
			}	
		}
		catch(StringIndexOutOfBoundsException ex) {//exception generated by charAt method
			System.out.println("String Length : "+(len-1));
		}
	}

}
